//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UserInterface.rc
//
#define IDS_APP_NAME                    1
#define IDS_POSSESSIVE_MORPHENE         2
#define IDS_WARN_BAD_DRIVER             3
#define IDS_WARN_NO_TNL                 4
#define IDS_ERR_CANNOT_READ_FILE        5
#define IDS_ERR_NOT_LATEST_FILE         6
#define IDS_ERR_MUST_LAUNCH_FROM_PATCHER 7
#define IDI_METIN2                      100
#define IDD_COLOR_DIALOG                101
#define IDC_CURSOR_NORMAL               102
#define IDC_CURSOR_ATTACK               104
#define IDC_CURSOR_CHAIR                105
#define IDC_CURSOR_DOOR                 106
#define IDC_CURSOR_NO                   107
#define IDC_CURSOR_PICK                 108
#define IDC_CURSOR_TALK                 109
#define IDC_CURSOR_BUY                  110
#define IDC_CURSOR_SELL                 111
#define IDC_CURSOR_PICKUP               114
#define IDC_CURSOR_CAMERA_ROTATE        139
#define IDC_CURSOR_HSIZE                140
#define IDC_CURSOR_VSIZE                141
#define IDC_CURSOR_HVSIZE               142
#define IDD_SELECT_LOCALE               143
#define IDR_VERTEXSHADER_LEAF_DYNAMIC_LIGHTING 150
#define IDR_VERTEXSHADER_LEAF_STATIC_LIGHTING 151
#define IDR_VERTEXSHADER_WINDYBRANCH_DYNAMIC_LIGHTING 152
#define IDR_VERTEXSHADER_WINDYLEAF_DYNAMIC_LIGHTING 153
#define IDR_VERTEXSHADER_WINDYLEAF_STATIC_LIGHTING 154
#define IDR_VERTEXSHADER_WINDYBRANCH_STATIC_LIGHTING 155
#define IDC_MATERIAL_AMBIENT_SLIDER_RED 1000
#define IDC_START                       1001
#define IDC_MATERIAL_AMBIENT_SLIDER_GREEN 1001
#define IDC_EXIT                        1002
#define IDC_MATERIAL_AMBIENT_SLIDER_BLUE 1002
#define IDC_LOCALE_LIST                 1003
#define IDC_MATERIAL_AMBIENT_PRINT_RED  1003
#define IDC_MATERIAL_AMBIENT_PRINT_GREEN 1004
#define IDC_MATERIAL_AMBIENT_PRINT_BLUE 1005
#define IDC_NATURE_AMBIENT_SLIDER_RED   1006
#define IDC_NATURE_AMBIENT_SLIDER_GREEN 1007
#define IDC_NATURE_AMBIENT_SLIDER_BLUE  1008
#define IDC_NATURE_AMBIENT_PRINT_RED    1009
#define IDC_NATURE_AMBIENT_PRINT_GREEN  1010
#define IDC_NATURE_AMBIENT_PRINT_BLUE   1011
#define IDC_LIGHT_COLOR_SLIDER_RED      1012
#define IDC_LIGHT_COLOR_SLIDER_GREEN    1013
#define IDC_LIGHT_COLOR_SLIDER_BLUE     1014
#define IDC_LIGHT_COLOR_PRINT_RED       1015
#define IDC_LIGHT_COLOR_PRINT_GREEN     1016
#define IDC_LIGHT_COLOR_PRINT_BLUE      1017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
